apiVersion: skaffold/v1beta12
kind: Config
build:
  artifacts:
  - image: react-example-app
    context: ../../
    docker:
      dockerfile: react-example-app/Dockerfile
      buildArgs:
        environment: development
  tagPolicy:
    sha256: {}
deploy:
  helm:
    releases:
    - name: '{{ .COMPONENT_PREFIX }}-react-example-app'
      chartPath: react-example-app
      valuesFiles:
      - react-example-app/values.yaml
      values:
        image: react-example-app
      namespace: default
      setValueTemplates:
        application.development.codebasePath: '{{ .COMPONENT_CODEBASE_DIRECTORY }}'