apiVersion: skaffold/v1beta12
kind: Config
build:
  artifacts:
  - image: XXXXX
    context: ../../
    docker:
      dockerfile: client/Dockerfile.production
      buildArgs:
        environment: production
  tagPolicy:
    gitCommit: {}
deploy:
  helm:
    releases:
    - name: '{{ .COMPONENT_PREFIX }}-client'
      chartPath: client
      valuesFiles:
      - client/values-production.yaml
      values:
        image: XXXXX
      namespace: production
      # setValueTemplates:
      #   ingress.annotations.external-dns\.alpha\.kubernetes\.io/hostname: '{{ .COMPONENT_PREFIX
      #     }}-app.example.com'
      #   ingress.hosts[0]: '{{ .COMPONENT_PREFIX }}-app.example.com'
