# Default values for react-example-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

application:
  port: 3000
  environment: development
  containerWorkDir: "/opt/app"
  development:
    codebasePath: "/tmp/ji/react-example-app"
  env:
    app:

image: react-example-app
imagePullPolicy: IfNotPresent
replicaCount:
  app: 1

service:
  type: NodePort
  port: 3000
  staticNodePort: false

ingress:
  enabled: false

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
