{{- if ne .Values.application.environment "development" }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "example-app.fullname" . }}-web
  labels:
    app: {{ template "example-app.name" . }}-web
    chart: {{ template "example-app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount.app }}
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: {{ template "example-app.name" . }}-web
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "example-app.name" . }}-web
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{.Values.image}}
          imagePullPolicy: {{.Values.imagePullPolicy}}
          command: ["/bin/sh", "-c"]
          args: {{.Values.application.startCommand.app}}
          ports:
            - name: http
              containerPort: {{.Values.application.port}}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /_status
              port: http
          readinessProbe:
            httpGet:
              path: /_status
              port: http
{{- with .Values.application.env.common }}
          env:
{{ toYaml . | indent 12 }}
{{- end }}
{{- with .Values.application.env.app }}
{{ toYaml . | indent 12 }}
{{- end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
{{- if .Values.application.runMigration }}
      initContainers:
        - name: migrations
          image: {{.Values.image}}
{{- with .Values.application.env.common }}
          env:
{{ toYaml . | indent 12 }}
{{- end }}
          command: ["/bin/sh", "-c"]
          args: {{.Values.application.startCommand.migration}}
{{- end }}
{{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}

---
{{- end }}