{{- if eq .Values.application.environment "development" }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "react-example-app.fullname" . }}-web
  labels:
    app: {{ template "react-example-app.name" . }}-web
    chart: {{ template "react-example-app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount.app }}
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: {{ template "react-example-app.name" . }}-web
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "react-example-app.name" . }}-web
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.application.port }}
              protocol: TCP
{{- with .Values.application.env.app }}
          env:
{{ toYaml . | indent 12 }}
{{- end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
          volumeMounts:
          - mountPath: {{ .Values.application.containerWorkDir }}
            name: app-volume
          resources:
{{ toYaml .Values.resources | indent 12 }}
      volumes:
        - name: app-volume
          hostPath:
            path: {{ .Values.application.development.codebasePath }}
            type: Directory
{{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}
---

{{end}}
