apiVersion: v1
kind: Service
metadata:
  name: {{ template "react-example-app.fullname" . }}-web
  labels:
    app: {{ template "react-example-app.name" . }}-web
    chart: {{ template "react-example-app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
{{- if .Values.service.staticNodePort }}
      nodePort: {{ .Values.service.nodePort }}
{{- end }}
      name: http
  selector:
    app: {{ template "react-example-app.name" . }}-web
    release: {{ .Release.Name }}
