apiVersion: skaffold/v1beta12
kind: Config
build:
  artifacts:
  - image: XXXX
    context: ../../
    docker:
      dockerfile: example-app/Dockerfile
  tagPolicy:
    gitCommit: {}
deploy:
  helm:
    releases:
    - name: '{{ .COMPONENT_PREFIX }}-example-app'
      chartPath: example-app
      valuesFiles:
      - example-app/values-production.yaml
      values:
        image: XXXX
      namespace: production
      setValueTemplates:
        application.env.common[0].value: '{{ .COMPONENT_PREFIX }}'
